### ISSUE TITLE
Plans for Tsumihoroboshi patch

### ISSUE THREAD

**Issue by enumag** [07th-mod/tsumihoroboshi#1]
With Tsumohoroboshi release a week from now I wanted to write down the plans since we have a lot more work to cover now than we did for the previous chapters and some of the steps are different than before.

I'd also like if you could confirm your plans to work on the parts you worked on before so that we could make alternative plans if someone is too busy to do their part.

-----

### 1. Geting the scripts

@ItaloKnox When you commit the scripts to this repository, put them into the Update directory. Puting them somewhere else complicates merging if MG later updates the game for typos.

### 2. Automatic voice insertion

As usual I'll use my old [tool](https://github.com/07th-mod/voice-inserter) to do this.

### 3. Manual voice insertion

@ItaloKnox Your part as usual. Keep in mind that we need to write down how this part works for the dev docs. It is not necessary for you to actually make a directory with just the voices for Tsumi at this point. And certainly don't worry about spectrum files. I'll handle that later.

### 4. Graphics patch

@Grelo Are you up for it this time too? Since the last time there were many changes in the structure of the graphics patch. You don't have to match it exactly, just try not to go too far from the new structure:

```
CG/
    background/ (copy-pased backgrounds from PS3, custom backgrounds should go into a different directory)
    scene/ (PS3 CGs)
    flashback/ (backgrounds and CGs with the flashback filter applied)
    text/ (this is where all the text sceens should go but I can easily do that after you're done)
    tips/ (directory for the tips screen, again can be done easily later)
    sprite/
        normal/
        sunset/
        night/
        flashback/
    portrait/
        normal/
        sunset/
        night/
        flashback/
```

The sprite and portrait directories should strictly use PS3 names. Disregard any MG naming. The final patches are using slightly different names than PS3 (because of linux) but don't worry about that. I'll fix that later.

It's alright If you miss some references to MG sprites or whatever in the scripts. I have a tool that detects such cases. Also if any part of this new naming structure is too much work with your current process then just leave it for us to fix later.

Also I think you can start working on this sooner than Italo is completely done with manual voice insertion. You can work on `tsumi_001` if Italo is already on `tsumi_005` or so.

On a side note you should not always use closed mouth expressions like you did with Meakashi. Whichever sprite variant you'll use at this point will be the one which would be used by the final patch when LipSync is disabled and will also affect the CGAlt sprites patch to some extent.

### 5. ADV mode update

When both manual voice insertion and initial graphics patch are done I need to use several of my tools:

- Convert everything to ADV mode.
- Detect any missing files.
- Convert sprite names from PS3 to our convention.
- Compile the graphics pack.
- Compile the voice pack.

This will be a lot of work and might take some time because it will actually be very different from the previous chapters. I'll have to update many of the tools before I can use them. Sadly I can't really prepare it beforehand. Also I need to document what I'm doing here for the dev docs.

@ItaloKnox As usual I'll need your help with the compilation of graphics and voice patches.

### 6. Initial release

EDIT: DoctorDiablo would like to do a spell check before the release.

At this point we will most likely make an initial release using vanilla DLL. Since it doesn't involve DLL hacking and we'll have the scripts checked for any missing files it should be relatively stable.

### 7. CGAlt patch

@jwgrlrrajn At this point you can start working on the MG sprites patch. This can be added as a separate release regardless on where we're with DLL and LipSync.

### 8. DLL hacking

@idealpersona Can we count on you to hack the Tsumi DLL with all the new features? I know this will be the first time for you to do this so I fully expect it will take a lot of time and might have some issues. That's completely fine.

Of course you can start working on this right after the game is released, without waiting for us.

I have a question for you here. Do you want to make all the edits at once or would you like to do general DLL changes first and LipSync later? I have separate commands here - one to update the scripts with DLL changes and second one for LipSync. I assume you'll need updated scripts for testing .I can run the commands separately or both at once whatever is better for you. Of course I'll need to update the commands to actually work with Tsumi.

Also I'd like to ask you to make some notes about what methods/classes/whatever need to be copied and edited for the new chapter. This will help up later when we work on Minagoroshi and future chapters.

### 9. LipSync update

As mentioned above I'll convert the scripts again using my other tools and then recompile the graphics patch to include LipSync variants for all sprites. I'll also need to recompile the voice pack with spectrum files.

### 10. New UI

@irlPM Can we count on you with this? It can be started pretty much immediately, except for the tips screen. If you're done early it could be a part of the initial release with the tips screen added later with LipSync release.

### 11. Poems & Text CGs & Tips screens

@Grelo @jwgrlrrajn @irlPM Inochi made some PSD templates we will use but he's not even done with these for Meakashi yet so I don't assume he'll have time for it. This should be quite easy (although possibly time consuming) for anyone familiar with photoshop. Not sure whom to assign this one. It's of course entirely possible for someone to make the text CGs and someone else to make the tips screens. Again these can be prepared at any point and could even go into the initial release if we have them quickly.

### 12. Beta release

When we're done with LipSync we'll make a beta release with all the features above (except UI and text/tips screens if they are not ready). Depending on the stability of the new DLL and other changes there might be a few more beta releases with bugfixes.

The final release should be made a few weeks after beta release I think.

After that we'll make plans for future changes like PS3 openings and a long list of other things.

------

Please confirm your plans about your participation for Tsumi patch and let us know if you're unavailable during that time period.

Personally I will be gone on June 17th but it should not affect the process because I can do automated voice insertion before I leave and voices and graphics won't be ready until I'm back anyway.

Is everyone ok with the process I outlined above? Did I forget anything important? Would you like change anything? Any suggestions are of course welcomed. Thanks for reading.

**Comment by irlPM** [comment]
I could to the new ui for sure, I can't do the tips screen though as a said I'm still reading higurashi so I don't wanna be spoilered. And what do you meant about the text cgs?

**Comment by Grelo** [comment]
Yes i am up for it. I have slightly less time but i will do my best!

**Comment by idealpersona** [comment]
I'm totally down.  I will start working on this as soon as it's released - all DLL changes in one pass.

**Comment by DoctorDiablo** [comment]
One more thing I'd like to do after the voice/graphics changes are squared away, but before the full release, is to run the scripts through spell check and fix any obvious typos.  It should take a day at most.

Aside from that, I don't have any specific responsibilities this time.  So feel free to ping me if anyone needs any help.

**Comment by enumag** [comment]
Thanks for the confirmations guys.

@DoctorDiablo Good idea. I noted that in the first post so that we don't forget.

**Comment by enumag** [comment]
Current status:

For voice patch I need to fix my voice pack compiler to work with PS2 voices. This will be done today or tomorrow.

We also need to look into the steam fix for looping and BGMs. According to the latest news from twitter Doddler will fix these but it will most likely take some time so we don't want to wait for him. My priority now is the voice pack but if noone else gets to integrating the BGM fix I guess I'll do that this weekend too.

For the Partial release we need to update the installer and prepare an unskippable warning screen.

Also Italo had some cool ideas he shared with me on Discord which we'll most likely want to include.

@ItaloKnox Can you write the text for the warning screen and create issues about your ideas while I work on the voices and BGMs?

**Comment by enumag** [comment]
Also I should give a report about the current status of the graphics patch. Grelo is done up to _tsum_006. You can see the progress in the [graphics-patch](https://github.com/07th-mod/tsumihoroboshi/commits/graphics-patch) branch.

**Comment by ItaloKnox** [comment]
Say no more, I'll have them done after a take a nice nap. Feeling kinda dead right now.

**Comment by ItaloKnox** [comment]
Here's what I came up with for the warning:

```
Warning! [at the top in big letters, everything centered]

You are about to play a very early version of the patch. This patch only covers a small portion of the game and is meant only for testing purposes. Beware that issues might happen, such as broken save files, missing character sprites, freezes and text issues in general.

By playing this version of the patch you agree in reporting any issues you find during your playthrough. Issues must be reported at goo.gl/685t1X (redirects to our repository).

Click to continue [at the bottom right corner]
```

Be free to edit as much as you want, I had some good ideas right after I woke up but I forgot everything.

**Comment by enumag** [comment]
@ItaloKnox Hmm... if we add Rena with construction hat on the screen, should we make it sound like Rena was saying it?

**Comment by enumag** [comment]
About the voice only patch... I fixed the voice pack compilation yesterday and merged the BGM fix this morning so we're pretty much ready to release it. That said, Doddler tweeted that he'll fix some bugs including the BGM issue and release it this weekend. Should we release now or wait for Doddler's fixes?

@DoctorDiablo Thanks for the spell check!

**Comment by Grelo** [comment]
It needs to say that the patch is not complete not early version of the patch, it's misleading.

**Comment by enumag** [comment]
Well it does say "This patch only covers a small portion of the game" after that but yeah maybe we should rewrite it a bit.

**Comment by enumag** [comment]
Here is the file to compile Tsumi voice pack. Remember that unless we wait for Doddler's fixes we also need to include the BGMs from the steam fix (scripts are merged).

https://www.dropbox.com/s/k5jm13zx42honfh/tsumihoroboshi-voices.sh?dl=0
https://steamcommunity.com/app/668350/discussions/0/2788173147741838077/

**Comment by ItaloKnox** [comment]
@enumag I think it can work with Rena. Or maybe we should just include her there as an extra. We can actually try both if someone can come up with a couple mockups.

Also, I agree with you and @Grelo about the wording. It can be a little misleading if you want it to be, so better to make sure to rewrite anything that can be taken in more than a single way. We can change ``You are about to play a very early version of the patch`` to ``You are about to play a work in progress version of the patch`` or just remove this sentence entirely.

Last but not least, I think we should hold on with the voices a bit. If we don't get a new update until 8 PM PDT today I will just post an announcement postponing the release until the update is released. The number of fixes seems to be significant enough for us to make sure our patch is 1:1 with them.

**Comment by DoctorDiablo** [comment]
Made a mockup for a warning screen.  I trimmed down some of the text because it was a bit too long to fit on one screen.  Even if we don't end up using it, I had fun making ridiculous construction Rena.

![partial_patch_warning](https://user-images.githubusercontent.com/20390474/42006285-ee95fc24-7a46-11e8-8cd1-05e4820bb4ef.png)
