### ISSUE TITLE
issues while playing through tsumi

### ISSUE THREAD

**Issue by HellaMadMax** [07th-mod/tsumihoroboshi#10]
First Tip "A Beautiful Day":

text is too long
https://steamuserimages-a.akamaihd.net/ugc/955210159014904766/AA83E6E20925886879A0F1101A285590864A7293/
*-- dev comment: TIPS NOT DONE*

"It was inevitable" doesn't appear on screen at all as the paragraph above takes up all the room https://steamuserimages-a.akamaihd.net/ugc/955210159014911626/DC66D4B600738B5970CF72DFA353692F06F4786B/
*-- dev comment: TIPS NOT DONE*

Chapter 2:

Rena says "Our duty as well!!" but it's added on the end of Keiichi's previous message
https://steamuserimages-a.akamaihd.net/ugc/955210159015006160/EB9BA3586BC52B8C6E8C25526535E728FE62AD2A/
*-- dev comment: FIXED*

text too long
https://steamuserimages-a.akamaihd.net/ugc/955210159015052618/2AB5A22854F3F3FA2C6E137F9A2B06964D5144DC/
https://steamuserimages-a.akamaihd.net/ugc/955210159015055511/10533A7EBE32F6B7E1FACF198AF3486330F4A5DF/
https://steamuserimages-a.akamaihd.net/ugc/955210159015059769/2243E8F53390FCE6256B8536C159120298BA25E2/
*-- dev comment: FIXED*

"can" and "category" are split mid-word in textlog
https://steamuserimages-a.akamaihd.net/ugc/955210159015070189/C3EBB776EA3F59AB1AB90A29E71D87A24DECF98F/
*-- dev comment: KNOWN / CAN'T FIX*

"come-from-behind" part is separate from the rest of what Keiichi said, and without his name at the top (maybe it's intentional?)
https://steamuserimages-a.akamaihd.net/ugc/955210159015187476/6BF4860EB06B30D2555307E5F004AAFE8ADA0F8F/
*-- dev comment: FIXED*

text too long in Second Tip "Business Card"
https://steamuserimages-a.akamaihd.net/ugc/955210159015208159/F6D2E93FA20381541A1740F685B5281F3F68FCC7/
*-- dev comment: TIPS NOT DONE*

Chapter 4:

missing Rena's name at the top
https://steamuserimages-a.akamaihd.net/ugc/955210159015422346/0A95FBC45444DA52CBAB1F9F8AE69676B4134DE0/
*-- dev comment: FIXED*

shows as Rina despite the conversation not revealing who the woman talking is at that point
https://steamuserimages-a.akamaihd.net/ugc/955210159015550385/F248C56313CAE16F052995F8F776597A77B36E46/
*-- dev comment: NOT A BUG*

no name attached to "Good. It's all here". Spoken by Rina
https://steamuserimages-a.akamaihd.net/ugc/955210159015556223/CF713647040AD143D1078349A51934DE7EC03F41/
*-- dev comment: FIXED*

Also worth mentioning the two guys they're talking to also have no name attached to their dialogue, maybe it should have a generic name like "Man" similar to the strangers outside the Angel Mort?
*-- dev comment: FIXED*

text too long in Tip "Property Estimate"
https://steamuserimages-a.akamaihd.net/ugc/955210159015549724/6021249350344B71F40EB6B1CFA57A17D018B1F6/
*-- dev comment: TIPS NOT DONE*

random line break after "that"
https://steamuserimages-a.akamaihd.net/ugc/955210159015684703/BFC266164D9EC3CDEE2F9E51A0A3CA925E949C98/
*-- dev comment: FIXED*

Chapter 6:

missing name, missing voice. not sure who it's meant to be
https://steamuserimages-a.akamaihd.net/ugc/955210159015794364/0A30A4A7BB6F48E8315D42E064FF792791339199/
*-- dev comment: FIXED* (the line belongs to Rika but voice is missing)

text too long
https://steamuserimages-a.akamaihd.net/ugc/955210159015871791/F9F91765A6B5CE90CB94E4714244CC2EBAD2551B/
*-- dev comment: FIXED*

"thought" split mid-word in textlog
https://steamuserimages-a.akamaihd.net/ugc/955210159015876648/3ABE5C205F3392A78A4D937460CF7855F7CFC22D/
*-- dev comment: KNOWN / CAN'T FIX*

missing name, Keiichi is speaking
https://steamuserimages-a.akamaihd.net/ugc/955210159016749251/45F9F1DEA1F9355BF3E5BB2FA036A41A0AE5E1A1/
*-- dev comment: FIXED*

**Comment by enumag** [comment]
TIPS are expected to be broken, they were not yet updated. We'll need to look into the rest. Thanks for reporting!

**Comment by enumag** [comment]
Textlog spliting is a known but we were unable to solve so far.

**Comment by enumag** [comment]
Missing Rena's name in chapter 4 doesn't make sense at all. According to script the text should be:

```
"Hau, I slept in this morning. I couldn't sleep last night."
```

Where did the Hau go?? Something weird is going on here. Also irl reported the same thing too in #11 so it doesn't seem like a random error. I'll look into it again later.

**Comment by enumag** [comment]
Rina's name is correct here. The player already knows her name at this point.

**Comment by enumag** [comment]
For that missing name in chapter 6, do you know whose line is it supposed to be?

**Comment by enumag** [comment]
@HellaMadMax The fixes are complete, thanks for reporting. If you find some more bugs open a new issue please. Thank you!

**Comment by enumag** [comment]
All fixed.
