### ISSUE TITLE
Issues Tsumi

### ISSUE THREAD

**Issue by irlPM** [07th-mod/tsumihoroboshi#11]
A line said by rena that it hasn't her name above it ![image](https://user-images.githubusercontent.com/33790743/42426447-7071c4fc-82fe-11e8-9611-8695285ab64a.png)

**Comment by irlPM** [comment]
![image](https://user-images.githubusercontent.com/33790743/42431504-44c29e94-831c-11e8-8edc-8f0951ff73ed.png)
tips out of the screen in adv mode

**Comment by enumag** [comment]
First issue already reported in #10.

Second issue is not a bug. TIPS were not yet updated and are not expected to work correctly.
