### ISSUE TITLE
New voice line cuts previous one short (on auto mode)

### ISSUE THREAD

**Issue by lilly19** [07th-mod/tsumihoroboshi#16]
When using auto mode, sometimes voice lines "overlap", or rather, a new line starts playing before the previous line has finished, cutting it off.
I didn't notice anything wrong in the "prologue", but the problem starts right away in the first chapter.
I tried adjusting auto mode message and advance speed, but that wasn't of any help.

**Comment by enumag** [comment]
Hmm, I believe we solved this in previous chapters. Not sure why it doesn't work in tsumi. We'll have to look into it.

**Comment by enumag** [comment]
Yeah it's broken in Tsumi.

@idealpersona This is DLL bug. If I remember correctly the waiting for voices in automode is custom-implemented for some of the Line_* modifiers. `Line_WaitForInput` and `Line_Normal` for sure. Maybe `Line_Continue` as well but I'm not exactly sure. The easiest way to test it is to go to config screen and move both `auto mode message speed` and `auto mode advance speed` to far right, then trigger auto mode. As far as I know it works fine in all previous chapters and I personally tested it today in Himatsubushi and Meakashi.

**Comment by idealpersona** [comment]
@enumag Can't reproduce with the new Higurashi-Assembly DLL.  May be solved now.

https://github.com/07th-mod/higurashi-assembly/raw/tsumi-mod/bin/Debug/Assembly-CSharp.dll

**Comment by enumag** [comment]
Can't run the game now, output_log says something about missing nipah.json. Where can I get that file?

**Comment by enumag** [comment]
Also is it supposed to fail like that if the file doesn't exist?

**Comment by enumag** [comment]
Indeed it works fine with that DLL. 👍
