### ISSUE TITLE
Trouble/Confusion in Installing Patch

### ISSUE THREAD

**Issue by nekuwafers** [07th-mod/tsumihoroboshi#17]
Hey there, trying to install the tsumihoroboshi patch, but encountering some trouble/confusion. So in the installation guide it mentions to put the files in the root folder with the .exe, which i found was in the MacOS folder (Mac user for reference), and I put the extracted files from the graphics patch, voices patch, movie patch, and 'patch' patch there. Unfortunately, nothing seemed to happen. I remembered that for chapter 1-4 I had installed the patch by working in Resources/Data/StreamingAssets, so I went back there. I had some success at the start (replaced the CG and CGAlt folders and the game started up fine, tho stayed on a black screen and eventually froze, probably because i had only brought in the CG and CGAlt files). However, I merged the patch's Update folder with the Update folder in Resources/Data/StreamingAssets, and now the game just stays on a silent, black screen when i start it up.

I figure either I'm doing this completely wrong or I'm just mixing a few things up. Any ideas on what I'm doing wrong? Thanks for the help!

**Comment by nekuwafers** [comment]
<img width="983" alt="screen shot 2018-10-02 at 9 26 17 pm" src="https://user-images.githubusercontent.com/43799667/46386922-d91a5180-c689-11e8-8213-4e8922ff97aa.png">

Here's what the unmodified game folder looks like immediately after opening the package contents. I tried stretching it out as much as possible, but let me know if there's a specific path you want a screenshot of

**Comment by nekuwafers** [comment]
The folder i thought was the root was MaxOS, since HigurashiEp06 seemed to be the executable. Would i be mistaken?

**Comment by ItaloKnox** [comment]
Looks great! It seems that OSX uses a different folder structure. In this case, if you open each file individually (any order as long as the patch file is the last one) and extract the content that is inside ``HigurashiEp06_Data`` in that file inside your ``Resources/Data`` folder it should work just fine. Just think that ``Resources/Data`` is the same as ``HigurashiEp06_Data`` on Linux and Windows.

I hope that was easy to understand, I'm going to update the tutorial to make sure this is covered and there's no more confusion for Mac users.

**Comment by nekuwafers** [comment]
Ok thanks, that makes a lot of sense. So In the case of the various patches, I've noticed they have StreamingAssets folders. Just wanna double check, but I assume I should be merging those with the existing StreamingAssets folder, rather than overwriting them

**Comment by nekuwafers** [comment]
I went along and merged the StreamingAssets folder, and it looks like we're good to go! So yea, treating Resources/Data as the root for Mac users seems to work perfectly. Thanks again for the help!

**Comment by ItaloKnox** [comment]
Yep, you are correct. :)

Sorry about the small radio silence, just had an internet outage here but looks like it's working again. Thankfully you got it to work without my help, merging/overwriting the folders is always encouraged in this patch. 😛 

Just reopen this issue if you need any more help!

**Comment by nekuwafers** [comment]
no worries my friend, thanks again!
