### ISSUE TITLE
Text box appearing irregularly

### ISSUE THREAD

**Issue by Ikkarin** [07th-mod/tsumihoroboshi#18]
Hi! This is my first time using this platform, so excuse me if this issue has been reported elsewhere before or is not being reported properly.

The text box is showing up where it normally shouldn't be (at least as with the previous chapters up to now). It appears right off the bat on the 07th Expansion screen, over the opening movie, the game's logo and the main menu as well. (strangely enough, it hides as normal during the MangaGamer screen to come back right after).

![image](https://user-images.githubusercontent.com/44866610/48196095-3c09a300-e330-11e8-86f4-51daa1b16cbf.png)

![sui](https://user-images.githubusercontent.com/44866610/48195942-c271b500-e32f-11e8-8018-bada2ca38883.png)

![image](https://user-images.githubusercontent.com/44866610/48196170-770bd680-e330-11e8-8cc9-189802668028.png)

**Comment by enumag** [comment]
Yeah this happens sometimes. It is quite rare so we didn't try to fix it yet. Perhaps we should.

**Comment by idealpersona** [comment]
This has been fixed and will hopefully be released soon.

**Comment by idealpersona** [comment]
It still will appear at first when you launch the game but it should go away after that.

**Comment by enumag** [comment]
Fixed in https://github.com/07th-mod/tsumihoroboshi/releases/tag/v1.3.0
