### ISSUE TITLE
[Spoiler] New CG

### ISSUE THREAD

**Issue by enumag** [07th-mod/tsumihoroboshi#2]
MG included a new CG in their Tsumihoroboshi release:

![](https://cdn.discordapp.com/attachments/384427599167750156/456698944228032512/re1_ev.png)

Most likely it is an equivalent for this PS3 CG:

![034](https://user-images.githubusercontent.com/539462/41401413-14030916-6fc0-11e8-9823-f81e0e4f61e2.png)

The issue with the MG CG is the 4:3 aspect ratio. Instead of croping it we could add an animation - show the bottom of the image first and then move the image down to show the top.

Since this will only be used if CGAlt is active we need a way to detect that in the scripts. There is most likely a global flag for that but I don't know the name.

@DoctorDiablo Since you're less busy than the others this time around, can I ask you to take care of it?

**Comment by DoctorDiablo** [comment]
Yep, there's a global flag for that.  I've figured out the code to get it displaying the appropriate image and doing the pan up for the MG version.  The timing could use some tweaking, depending how it looks in the scene.
`	if(GetGlobalFlag(GArtStyle) == 0)
	{
		//PS3 CG
		DrawScene("scene\034", 500);
	}
	else
	{
		//MangaGamer CG
		DrawBustshot(4, "scene\MGCG", 0, -80, -134, FALSE, 0, 0, 0, 0, 0, 0, 0, 1, 500, FALSE );
		MoveBustshot( 4, NULL, 0, 80, -134, 4, 5000, TRUE );
	}`

**Comment by enumag** [comment]
@DoctorDiablo Awesome! I just formated the code a little.

@Grelo I think you should be able to use this once you get to that part.
