### ISSUE TITLE
Translation meaning

### ISSUE THREAD

**Issue by orian34** [07th-mod/tsumihoroboshi#20]
https://github.com/07th-mod/tsumihoroboshi/blob/35e30314e2c2d5c8b9e3433ab213c963d1b7f342/Update/_tsum_001.txt#L4300

@Norgus 
Mmh, Isn't there a mistake? I don't really understand what this sentence means in the context. What does the japanese version say?

**Comment by Norgus** [comment]
This line is more like "That aside...".

Funny enough, I think Keiichi's line after it is more wrong!

it's translated as "\"You're pretty good at that.\"" - as if Keiichi is praising Rena's game, when really he's commenting on what a good diversion Mion has managed to create to distract everyone into forgetting her loser's punishment. 

Also, Rena's line "\"Mii-chan, you're trying to get away without suffering the punishment, aren't you?\"" is translated as if she were addressing Mion directly, when actually she's addressing Satoko and explaining about Mion in the third person.

Guess I'll push a fix in a minute.

**Comment by ItaloKnox** [comment]
さすが Norgus. That's the development I wasn't expecting from this issue. lol

**Comment by Norgus** [comment]
Done! Hopefully not worded too poorly. 9e7a1c340c59cae243ef1b5391b98a9416620c02

**Comment by enumag** [comment]
Thank you @Norgus!
