### ISSUE TITLE
Chapter Jump Unlock

### ISSUE THREAD

**Issue by orian34** [07th-mod/tsumihoroboshi#25]
There's something wrong with how the champter jump unlocks days.
Near day 20 I didn't even have beyond day 11.

It's a bit difficult to track, but I think that the script adds 1 day per chapter part.(I think there's around 13?)

Once you reach the end, all become unlocked.
 
(You can see something is wrong by how I labeled my edits in these past days.)

**Comment by orian34** [comment]
Only answer arcs have the issue since question arcs don't have enough days to have a day that isn't a full chapter.
@idealpersona

**Comment by enumag** [comment]
Should be solved by https://github.com/07th-mod/tsumihoroboshi/commit/d21474b0367d5bcf422ec4f634e414d91e7d3b16
