### ISSUE TITLE
CG Staffroll Text Typos

### ISSUE THREAD

**Issue by orian34** [07th-mod/tsumihoroboshi#28]
![image](https://user-images.githubusercontent.com/12663654/50402912-abc9d500-079a-11e9-8081-ede4f1004281.png)
Service.
![image](https://user-images.githubusercontent.com/12663654/50402938-dcaa0a00-079a-11e9-9990-1867c69aa1f4.png)
![image](https://user-images.githubusercontent.com/12663654/50403024-aae57300-079b-11e9-8d02-5558ef4b7c44.png)
Ryuugu.

**Comment by enumag** [comment]
Here is the [image](https://user-images.githubusercontent.com/539462/57156113-7898f180-6ddd-11e9-9d97-bc81f975aad7.png) that needs to be edited.
