### ISSUE TITLE
New release instructions

### ISSUE THREAD

**Issue by enumag** [07th-mod/tsumihoroboshi#33]
CG:
- take the CG from current release (https://07th-mod.com/rikachama/Tsumihoroboshi-CG.7z)
- merge the CG directory from [this zip](https://github.com/07th-mod/tsumihoroboshi/archive/master.zip) into the current one as well, again overwrite all
- run https://www.dropbox.com/s/zvqwykaqemdd20r/tsumihoroboshi-sprites.sh?dl=1
- merge the CG directory generated by the script into the current one, overwrite all files
- ignore the generated CGAlt directory

CGAlt:
- take the CG from current release (https://07th-mod.com/rikachama/Tsumihoroboshi-CGAlt.7z)
- merge the CGAlt directory from [this zip](https://github.com/07th-mod/tsumihoroboshi/archive/master.zip) into the current one, overwrite all
- merge the [files](https://www.dropbox.com/s/w75g5nof9pn3q15/tsumi-missing.7z?dl=1) from TheDoctor into the CGAlt directory

**Comment by ItaloKnox** [comment]
Done! 👍
