### ISSUE TITLE
Tsumi bad endings

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/tsumihoroboshi#34]
@enumag There are actually two bad endings in Tsumi, and the first one is implemented in an overly complex way.  You don't actually make a choice that leads you to bad end 1.  If you haven't read Yoigoshi yet it forces you down the path to BE1, but if you have then it forces you toward the good ending (and there's no way to get bad end 1 again other than using chapter jump).  The path to bad end 1 diverges [right here in the script](https://github.com/07th-mod/tsumihoroboshi/blob/master/Update/_tsum_024_1.txt#L963), which happens [in the middle of this scene](https://youtu.be/CFypq-ONGb0?t=604).

Bad end 2 is much simpler.  It branches based on a choice that appears [right here in the script](https://github.com/07th-mod/tsumihoroboshi/blob/master/Update/_tsum_026.txt#L1459)
 which happens [right here](https://www.youtube.com/watch?v=dqXAb65paME)

Here are the generated script files:
[tsum_badend1.txt](https://github.com/07th-mod/tsumihoroboshi/files/3327534/tsum_badend1.txt)
[tsum_badend2.txt](https://github.com/07th-mod/tsumihoroboshi/files/3327535/tsum_badend2.txt)

**Comment by enumag** [comment]
@DoctorDiablo Can't detect if the player has read Yoigoshi here... Do you think we could add another choice for the bad end 1?

**Comment by DoctorDiablo** [comment]
Yeah, we could easily add a choice and branch based on the result.  But what should we make the choice say?  "Original Ending" / "Alternate Ending" ?

**Comment by enumag** [comment]
Unless we can come up with a choice that would make sense in the story, yes, I think so.

**Comment by orian34** [comment]
That shouldn't be too difficult

**Comment by Grelo** [comment]
In that case readers should be notified that they are no longer getting authentic, original higurashi experience downloading this mod but a 07th Mod modified one. In the installer would be the best.

**Comment by enumag** [comment]
Bad ends has been added and released some time ago.
