### ISSUE TITLE
Irie's outfit randomisation

### ISSUE THREAD

**Issue by tlm-2501** [07th-mod/tsumihoroboshi#35]
In the original game, Irie's outfit is randomised between three options (casual, doctor, baseball) in the [scene where he shows up in Angel Mort](https://github.com/07th-mod/tsumihoroboshi/blob/master/Update/_tsum_003_3.txt#L46). This was removed by MG for unknown reasons, but should probably be added back in because it's a pretty hilarious and weird detail.

**Comment by enumag** [comment]
I have this implemented locally, just waiting for CGAlt sprites.
