### ISSUE TITLE
Chapter 13 scene stuck - When Rika jumps

### ISSUE THREAD

**Issue by TraceStar** [07th-mod/tsumihoroboshi#36]
Hello,

Me again. Meakashi was completed without issues. Found an issue in Tsumihoroboshi. Here's a save file and the log. 

Seems to be this error:
`Could not find texture asset portrait/night/ri1_fuman_a1_0 in Console`

I made a night folder inside portrait and copied all the portraits into it and the scene played fine afterwards.

[Player.log](https://github.com/07th-mod/tsumihoroboshi/files/3882741/Player.log)
[save011.zip](https://github.com/07th-mod/tsumihoroboshi/files/3882750/save011.zip)

**Comment by enumag** [comment]
Fixed by https://github.com/07th-mod/tsumihoroboshi/commit/2a7f537834f35fb9ac2c1aa1b137b7bf84808d21

Sorry, this one slipped us since the usage is a bit unusual. Thanks for reporting, we'll release a fixed version soon.
