### ISSUE TITLE
Large chunks of missing voices

### ISSUE THREAD

**Issue by ItaloKnox** [07th-mod/tsumihoroboshi#4]
As discussed on Discord, Tsumi doesn't look too good at this moment. ``_tsum_002_2`` has at least 50 missing voices, which is a lot compared to the previous chapters. This should be very time consuming if I stopped to look for PS2 voices in every script looking like this, so I need help with those until I finish all 26 scripts + tips. I should come back to this issue to fix what can be fixed by the time we push the first release.

As suggested by @enumag, I think @DoctorDiablo should be a good one to help me around with this, since it might require some japanese knowledge. There are very large chunks of voices missing, so we have just a few places to start. If you open the script and search for ``PlaySE(4, "", 128, 64);`` you should find all 50 instances of missing voices. I already went through the script so it should be safe to assume about 30 of these are real, the rest should be false positives resulting from split voices.

Other issues (mostly minor) can be found [here](https://github.com/07th-mod/tsumihoroboshi#known-issues-for-fixing), but ``_tsum_002_2`` should be our priority for release.

**Comment by DoctorDiablo** [comment]
Looks like plenty of these are present in the ps2 version, so it shouldn't be too hard to add them all back in. (just tedious...)

Refresh my memory, what exactly do I need to do to add the ps2 files to the release?  Do I need to upload the .oggs to the repository?  And what path should I use when I add them?  The ps2 version has a weirdly different folder structure, right?  Should I append ps2/ to the start of the paths?

**Comment by ItaloKnox** [comment]
The path should be the same as the PS3 voices, but with a minor change: ``ps3/s19/04/990400040`` would turn into ``ps2/04/990400040``. I'm pretty much positive it works this way, but I think you should wait for @enumag to wake up so he can explain it better or correct me if I said it wrong. He probably knows if the files also need to be pushed right now or if we can use these paths to compile the voice patch later. Sorry, I couldn't be really helpful.

**Comment by DoctorDiablo** [comment]
Ok, just pushed the changes to `tsum_002_2`  I bumped the volume up to 240 on these since that's what we've usually done.

I'm heading out of town this weekend, but I can help more on Sunday.  Let me know if there are any others you want me to look at.

**Comment by DoctorDiablo** [comment]
Marking this closed, because all the voice issues are either fixed or unfixable.
