### ISSUE TITLE
No sound at all + few other issues

### ISSUE THREAD

**Issue by SimonAfek** [07th-mod/tsumihoroboshi#41]
**The problem**: There are a few of them.

- Apart from the intro movie, the game produces no sound at all. No background SFX, no voices when characters speak, nothing. I've checked to make sure the volume sliders are set appropriately, and that the application isn't muted in the Windows audio mixer.
- The UI also seems "wrong". The font is different to what it's been in all the previous installments (I think it might be Times New Roman? It looks very "default font selection". No black border around the letters, just plain white), and the little bouncing arrow icon that indicates you're at the end of the current line and need to click to continue is missing.

**The mod variant**: Full, with BGM and SE fixes selected.

**I bought the game at**: Mangagamer (Answer Arcs bundle)

**My operating system is**: Windows

**I installed the patch**: Using the Installer (v 1.1.51)

**Mod Download and Install Date**: Downloaded and installed today

**Additional info:** In order to verify that the problem isn't on my end, I uninstalled the game (removing the game folder and saves folder entirely afterwards), and then re-installed in order to check that the base game functioned correctly (it did). Installing the patch then reproduced the problem exactly as before.

**Comment by enumag** [comment]
Ar you sure your base game is up to date? If so, can you send us the output_log.txt file? (See "Getting Higurashi Log Files" at https://07th-mod.com/wiki/Higurashi/support/)

Most likely we'll also need your `sharedassets0.assets.backup` and `sharedassets0.assets.resS.backup` files.

**Comment by SimonAfek** [comment]
I'm fully certain my game is up to date - I downloaded it from Mangagamer earlier today.

`sharedassets0.assets.resS.backup` doesn't seem to exist, but here are the other two:

[output_log.txt](https://github.com/07th-mod/tsumihoroboshi/files/5011104/output_log.txt)

[sharedassets0.assets.backup.zip](https://github.com/07th-mod/tsumihoroboshi/files/5011105/sharedassets0.assets.backup.zip)

Also, in case it's relevant, the installer log says that the detected Unity version is `5.6.7f1`

**Comment by enumag** [comment]
@ItaloKnox This is the same as the bundled Tsumi issue we got reported on Discord recently which I tried to fix. From this it seems that the fix doesn't work as intended. Perhaps we should switch this Tsumi version to the downgrade treatment same as Matsu?

**Comment by enumag** [comment]
@SimonAfek Could you try to reinstall the game back to vanilla (without patch) and send me both `sharedassets0.assets.resS` and `sharedassets0.assets`?

**Comment by SimonAfek** [comment]
Sure thing. Here you go:

[sharedassets0.assets.zip](https://github.com/07th-mod/tsumihoroboshi/files/5011124/sharedassets0.assets.zip)
[sharedassets0.assets.resS.zip](https://github.com/07th-mod/tsumihoroboshi/files/5011127/sharedassets0.assets.resS.zip)

**Comment by enumag** [comment]
okay, install the patch now, I'll try to recompile the UI files for you in a minute

**Comment by enumag** [comment]
Try this. https://www.dropbox.com/s/7ipk5aipaglhmsy/Tsumihoroboshi-UI_5.6.7f1_win.7z?dl=0
It most likely won't work in which case I think we'll have to go ahead with the downgrade.

**Comment by SimonAfek** [comment]
I re-installed the patch and then extracted that dropbox archive over the existing `sharedassets0.assets`, and can confirm that this did not fix the issue.

Thanks for being so fast to respond by the way!

**Comment by ItaloKnox** [comment]
Hey, finally got here. We can try something that has worked before for the other person with the same error as you. It will take a couple more steps than running the installer and pressing install, but if you give me the ok, I will make sure to deploy it in production so other people won't have the same issue again.

Do this on a clean copy:
1. Download and extract [this file](https://07th-mod.com/ui.php?chapter=tsumihoroboshi&os=unix&unity=5.5.3p3
) inside your game folder. Overwrite the files.
2. Run the installer once again and install the patch normally. **Running the game in this step will result in a black screen. This is expected.**
3. Download the compatibility pack [from this link](https://dl.dropboxusercontent.com/s/tg3lb23r89ue09r/Tsumihoroboshi-System.7z) and extract it inside your game folder. Overwrite the files.
4. Run the game and please report back your results.

**Comment by SimonAfek** [comment]
Before I do this: Your first link says `os=unix` - I'm on Windows. Is that still the file I need to use?

**Comment by ItaloKnox** [comment]
Sorry, got the links mixed up. This should be what you need: https://07th-mod.com/ui.php?chapter=tsumihoroboshi&os=win&unity=5.5.3p3

Thanks for noticing it, you saved us from dooming this issue.

**Comment by SimonAfek** [comment]
1. Even after extracting the `5.5.3.p3` UI pack over the clean install, the installer still detects the game's Unity version as `5.6.7f1`. It downloads the `5.6.7f1` UI file during installation.
2. Running the game after performing step 2 did **not** result in a black screen, but rather, the game ran in the same faulty state as described in the opening comment of this issue
3. Extracting the compatibility pack from step 3 after this point caused the game to boot up stuck in a black screen

Ran it through twice, just to be sure. Once where I tried to run it after step 2 to see if it'd boot up into a black screen like you said, and then (after removing both game folder and save folder) running through the whole process without booting the game up until after step 3. Same result both times.

`output_log.txt` contains this line a whole bunch of times:

```
Invalid serialized file version. File: "K:/Games/Higurashi/Higurashi Chapter 6/HigurashiEp06_Data/sharedassets0.assets". Expected version: 5.5.3p3. Actual version: 5.6.7f1.
```

**Comment by SimonAfek** [comment]
I tried extracting the `5.5.3p3` UI pack again after doing all the steps you listed, and that seems to have made it work.

**Comment by SimonAfek** [comment]
@ItaloKnox This leads to a working, modded game:

1. Clean installation of base game
2. Use the python patcher to install the mod
3. Extract [Tsumihoroboshi-UI_5.5.3p3_win.7z](https://07th-mod.com/ui.php?chapter=tsumihoroboshi&os=win&unity=5.5.3p3) and the [Tsumihoroboshi-System.7z](https://dl.dropboxusercontent.com/s/tg3lb23r89ue09r/Tsumihoroboshi-System.7z) archive you linked in your comment into the game folder, overwriting all files when asked.

**Comment by ItaloKnox** [comment]
It is weird that the installer is detecting the wrong UI even after you
overwrite it. Since the installer can support it, you can shift the steps
around a bit. Install the patch normally, then add the UI and lastly the
compatibility pack. Otherwise, you can also try installing it manually if
the installer is still not behaving correctly.

Em sáb, 1 de ago de 2020 20:46, SimonAfek <notifications@github.com>
escreveu:

**Comment by drojf** [comment]
italo - in this comment: https://github.com/07th-mod/tsumihoroboshi/issues/41#issuecomment-667598108

you said 2. run the installer, **then** "3. Download the compatibility pack from this link and extract it inside your game folder."

The UI version is only changed when you extract the compatibility pack, so I'm assuming you meant to extract the compatibility pack first, then run the installer?

Simon also said:

> Even after extracting the 5.5.3p3 UI pack over the clean install, the installer still detects the game's Unity version as 5.6.7f1. It downloads the 5.6.7f1 UI file during installation. I did explicitly overwrite the existing sharedassets0.assets before running the installer.

This would be normal, as the version is stored in the `resources.assets` file, not the UI file.

**Comment by ItaloKnox** [comment]
@drojf your explanation at the end makes a lot of sense. I thought it was reading the sharedassets0 file to get the version. In fact, I believe I got an excerpt of the installer that did this function before for @enumag, hence the confusion.

With this in mind, then yeah: install patch, extract UI and then finally extract the compatibility pack.

For some reason I also didn't get @SimonAfek's last message via e-mail. Probably Thunderbird on my always-on PC messing my phone gmail notifications again.

Simon, I suppose you already got it to work as intended, right? If you believe the game is stable with this setup, please let me know, so I can update the installer and make sure no one has to go through this mess again.

**Comment by drojf** [comment]
> install patch, extract UI and then finally extract the compatibility pack.

I think if you just did:

1. Extract the compatibility pack (to set the version in the `resources.assets` to 5.5.3p3)
2. Install patch (which should install the 5.5.3p3 UI)

the installer should read the correct version from the compatibility pack (5.5.3p3) and then install the correct UI file automatically. 

I'm assuming the installer wouldn't overwrite any important files from the compatibility patch - if it does then the above may not work.

**Comment by tellowkrinkle** [comment]
I purposefully do the game version detection on a file we don't normally overwrite, so that if a user accidentally installs the wrong version and then tries to run the installer, it should fix it for them

**Comment by drojf** [comment]
ah thanks tellow

> If you believe the game is stable with this setup, please let me know, so I can update the installer and make sure no one has to go through this mess again.

ah sorry I may have misread what you meant. Yea, if we're updating the installer then the steps you said are correct (just the same as what we do with matsuribashi GOG

**Comment by SimonAfek** [comment]
As far as I can tell, both of these methods work. From a clean install, using the automated patcher:

1. Install patch
2. Manually extract 5.5.3p3 UI pack and compatibility pack

**OR**

1. Manually extract compatibility pack
2. Install patch

I've clicked/skipped through to the middle of the water gun fight on day 1, and everything seems good.

**Comment by ItaloKnox** [comment]
Thanks, I will update the installer later today to deploy the compatibility pack automatically. Please keep this issue open for now.

**Comment by ItaloKnox** [comment]
The fix is now deployed, though I can't really test it since I don't own this version of the game. If you are willing to give it a try, let me know the results. The installer should now do all the work to get it running the same way you are running it now.

**Comment by SimonAfek** [comment]
Just tried it on a clean install, and it seems to have worked - just playing through the first couple of lines, everything looks (and sounds) good.
