### ISSUE TITLE
Something about the patch

### ISSUE THREAD

**Issue by fsouzas** [07th-mod/tsumihoroboshi#8]
Hello. So I was looking your plans for the patch and everything looks great, but I, probably the only person 🤔, don't need all that lipsync or ADV mode.I just want to play the VN ASAP with all the cool PS3 assets. Is going to be an alternative patch for just the ps3 assets(voices, sprites, cgs) or are you guys going to pass this one?

Thanks for the hardwork!

**Comment by ItaloKnox** [comment]
Won't happen. These features are part of the patch and the tools are now tailored to make them. They won't make the patch be released slower or faster, it has no real weight in the process at this point. What makes the patch take time to be finished is the process of playing through the console game and make changes manually to the scripts.

If you don't like these features, they are all optional like before. You can change from ADV mode to NVL mode using the **F1** button, and disable lipsync using the **7** button.

**Comment by fsouzas** [comment]
Oh, thanks for the quick response, and for taking the time to explain it.

As my question was already answered you can close this issue.

**Comment by ItaloKnox** [comment]
Thanks, I hope you enjoy the patch. We're working really hard to have it released as soon as possible. 👍
