### ISSUE TITLE
Extra features for Tsumi (team credits, mod tutorial, intro logo)

### ISSUE THREAD

**Issue by ItaloKnox** [07th-mod/tsumihoroboshi#9]
I suggested these while talking to @enumag a few days ago and completely forgot to post about them. I feel like it's already time we give ourselves a bit of credit for the work in-game and expand further on the new mod shortcuts. Below I will explain every feature:

#### Mod tutorial

This should be as easy to implement and make as the warning screen at the start of our early access version of the patch. It should be added right after the player click on the ``start`` button and use the same background for a seamless transition. I'm talking about this screen (if I recall correctly this is what we call the scenario): 

![firefox_2018-06-21_20-57-22](https://user-images.githubusercontent.com/4702556/41751073-ca179642-7595-11e8-84b3-f76f8f9e6913.jpg)

I think I can do it but I need two things:
1. the fonts used in scenario screen (pictured in the screenshot)
2. the background we're going to use in Tsumi

The tutorial should be very simple and cover all the keyboard shortcuts we added and a short description of what they do.

#### Team credits

Self-explanatory. Whenever there are credits for the people at 07th and MG, I think we should add a short section with everyone who worked on the patch. This might prove to be a little annoying over time but can be manageable (and make everyone feel nice about themselves too).

#### Intro logo

We discussed this before and now I think it's time we settled for an actual logo for the group. The official name is 07th Modding, so let's try to come up with something cool. I came up with this some time ago: 

![07thmod](https://user-images.githubusercontent.com/4702556/41751174-87a5751c-7596-11e8-9ec3-4e9bb67250a3.png)

I believe we can go over the top and try anything, it doesn't have to be a single logo in a white background. Everyone is encouraged to try!

**Comment by enumag** [comment]
Mod tutorial would be a great addition with the many custom keys we're using. In my opinion it should also include the keys from the original game the game doesn't communicate them anywhere.

Personally I don't really care about being mentioned on some credit screen or list but I certainly want to give credit to all the other people working on this. We should also update the lists in the README since they are completely outdated. Does every chapter has credits for 07th and MG? Do we want to just list our nicknames or should we include notes about our contributions?

This logo is so dark I can't even see it with my monitor settings lol.

**Comment by ItaloKnox** [comment]
Yeah, I think it would be really cool to have all shortcuts. Is there anything more I didn't list [in the wiki](https://github.com/07th-mod/guide/wiki/Higurashi-Part-2---Patch-configuration-and-keyboard-shortcuts)?

Looks like every chapter has at least one end roll script, so I think this might be the case. Though if I recall correctly, Tatari's credits are handled in a different way. Most likely a longer version with scrolling text. Now, how we should do ours I don't really know. Maybe we should just follow the same pattern if MG did the same for them?

Also, you have a point lol. I'm running an IPS with 2.0 gamma (0.2 less than the default, most used by people working on graphics) so it will look darker for you than for me. Here, I doubled the brightness: 

![41751174-87a5751c-7596-11e8-9ec3-4e9bb67250a3](https://user-images.githubusercontent.com/4702556/41773788-a05a0bec-75f3-11e8-9a82-a209399fcf98.png)

**Comment by idealpersona** [comment]
Lol @ItaloKnox I seriously thought you uploaded a black screen at first.  Very avant-garde.

One of the suggestions I made a while back was to use a familiar font for 07th, but a totally distinct font for "mod" / "MOD" / "Mod"

**Comment by Grelo** [comment]
Don't forget that 07th Modding is not only Higurashi but includes Umineko too. So something related to both.

**Comment by ItaloKnox** [comment]
@Grelo I don't think this distinction really matters because we're pushing the image to Higurashi, we can have the same thing on Umineko as well. The most important thing should be the actual logo (just the name), the other stuff we add to make it cooler can be totally only about Higurashi if we're pushing it to Higurashi.

@idealpersona "mod" was because "modding" would take a lot of space in the URL so I wanted to make things simple. Actually, it was "higurashimod" before or something like that. I prefer "07th Modding", but if you guys can make it work in some other way, there's no problem. Let's take anything until we decide on the actual image.

**Comment by ItaloKnox** [comment]
Thanks to @Grelo's gigantic .psd with everything we could ever need about the scenarios, I finished the tutorial. It should be self-explanatory: just make the scenario text dissolve and use this one afterward. Then the user clicks to continue (can be a button or just nothing, it should be easy to understand that clicking would skip it).

I wish I could make it less messy but the layout doesn't really help, so that's what I could make out of it. If anyone has a better idea, we still have a lot of time to finish this.

![tsumi-tutorial](https://user-images.githubusercontent.com/4702556/42065185-e0089684-7b0f-11e8-87b1-7059b42cba63.png)

**Comment by yagamisempai** [comment]
random question.
what is the UI MOD?
 thank you for all this nwn

**Comment by enumag** [comment]
Logo is now added to all chapters.

**Comment by enumag** [comment]
Logo and mod tutorial are in the games now. Team credits is a wiki page. So this can be considered as solved.
